import { Course } from "@/types/course";

export const courses: Course[] = [
  {
    id: 1,
    nombre: "React con TypeScript",
    descripcion: "Aprende a construir aplicaciones modernas con React y TypeScript desde cero hasta nivel avanzado.",
    categoria: "Frontend",
    duracion: 48,
    imagen: "https://loremflickr.com/400/250/react,javascript",
    estado: "Activo",
  },
  {
    id: 2,
    nombre: "Node.js y Express",
    descripcion: "Desarrollo de APIs RESTful con Node.js y Express. Incluye autenticación y base de datos.",
    categoria: "Backend",
    duracion: 40,
    imagen: "https://loremflickr.com/400/250/nodejs,backend",
    estado: "Activo",
  },
  {
    id: 3,
    nombre: "React Native para Mobile",
    descripcion: "Crea aplicaciones móviles multiplataforma para iOS y Android con React Native.",
    categoria: "Mobile",
    duracion: 60,
    imagen: "https://loremflickr.com/400/250/mobile,smartphone",
    estado: "En Progreso",
  },
  {
    id: 4,
    nombre: "AWS Cloud Fundamentals",
    descripcion: "Fundamentos de Amazon Web Services: EC2, S3, Lambda, RDS y arquitecturas cloud escalables.",
    categoria: "Cloud",
    duracion: 35,
    imagen: "https://loremflickr.com/400/250/cloud,server",
    estado: "En Progreso",
  },
  {
    id: 5,
    nombre: "Docker y Kubernetes",
    descripcion: "Contenerización de aplicaciones con Docker y orquestación con Kubernetes en producción.",
    categoria: "DevOps",
    duracion: 45,
    imagen: "https://loremflickr.com/400/250/docker,container",
    estado: "Activo",
  },
  {
    id: 6,
    nombre: "Python para Data Science",
    descripcion: "Análisis de datos con Python, Pandas, NumPy y visualizaciones con Matplotlib y Seaborn.",
    categoria: "Data Science",
    duracion: 55,
    imagen: "https://loremflickr.com/400/250/datascience,python",
    estado: "En Progreso",
  },
  {
    id: 7,
    nombre: "Vue.js 3 Completo",
    descripcion: "Domina Vue.js 3 con Composition API, Pinia, Vue Router y despliegue en producción.",
    categoria: "Frontend",
    duracion: 42,
    imagen: "https://loremflickr.com/400/250/javascript,programming",
    estado: "Finalizado",
  },
  {
    id: 8,
    nombre: "Machine Learning con Python",
    descripcion: "Introducción al aprendizaje automático con scikit-learn, regresión, clasificación y clustering.",
    categoria: "Data Science",
    duracion: 70,
    imagen: "https://loremflickr.com/400/250/machinelearning,ai",
    estado: "Finalizado",
  },
];
